import {
  Archive,
  Bird,
  BookOpen,
  Box,
  Bug,
  Building2,
  Castle,
  Compass,
  Crown,
  Eye,
  Feather,
  Flame,
  Folder,
  Cog,
  KeyRound,
  Leaf,
  Lock,
  Map,
  Moon,
  Mountain,
  Orbit,
  Radio,
  Waves,
  Scroll,
  Shield,
  Skull,
  Sparkles,
  Star,
  Sun,
  Sword,
  TreePine,
  Wrench,
  VenetianMask
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const projectIcons: { name: string; label: string; Icon: LucideIcon }[] = [
  { name: "folder", label: "Folder", Icon: Folder },
  { name: "book", label: "Book", Icon: BookOpen },
  { name: "archive", label: "Archive", Icon: Archive },
  { name: "box", label: "Box", Icon: Box },
  { name: "scroll", label: "Scroll", Icon: Scroll },
  { name: "feather", label: "Feather", Icon: Feather },
  { name: "bird", label: "Bird", Icon: Bird },
  { name: "moth", label: "Moth", Icon: Bug },
  { name: "butterfly", label: "Butterfly", Icon: Sparkles },
  { name: "leaf", label: "Leaf", Icon: Leaf },
  { name: "tree", label: "Tree", Icon: TreePine },
  { name: "mountain", label: "Mountain", Icon: Mountain },
  { name: "river", label: "River", Icon: Waves },
  { name: "flame", label: "Flame", Icon: Flame },
  { name: "sun", label: "Sun", Icon: Sun },
  { name: "moon", label: "Moon", Icon: Moon },
  { name: "star", label: "Star", Icon: Star },
  { name: "planet", label: "Planet", Icon: Orbit },
  { name: "crown", label: "Crown", Icon: Crown },
  { name: "shield", label: "Shield", Icon: Shield },
  { name: "sword", label: "Sword", Icon: Sword },
  { name: "skull", label: "Skull", Icon: Skull },
  { name: "eye", label: "Eye", Icon: Eye },
  { name: "mask", label: "Mask", Icon: VenetianMask },
  { name: "key", label: "Key", Icon: KeyRound },
  { name: "lock", label: "Lock", Icon: Lock },
  { name: "wrench", label: "Wrench", Icon: Wrench },
  { name: "gear", label: "Gear", Icon: Cog },
  { name: "building", label: "Building", Icon: Building2 },
  { name: "city", label: "City", Icon: Castle },
  { name: "map", label: "Map", Icon: Map },
  { name: "compass", label: "Compass", Icon: Compass },
  { name: "radio", label: "Signal", Icon: Radio }
];

export function ProjectIcon({ name, color, size = 22 }: { name: string; color: string; size?: number }) {
  const found = projectIcons.find((item) => item.name === name) ?? projectIcons[0];
  return <found.Icon size={size} color={color} />;
}
